### ISSUE TITLE
FreemarkerViewsRenderer swallowed template exceptions

### ISSUE THREAD

**Issue by Andy2003** [micronaut-projects/micronaut-views#11]
If a template is malformed, there is no log output that informs the user of the error location.

swallowed exception:

    freemarker.core.ParseException: Syntax error in template "xxx.ftlh" ...
	    at freemarker.core.TokenMgrError.toParseException(TokenMgrError.java:260)
	    at freemarker.template.Template.<init>(Template.java:269)
	    at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:549)
	    at freemarker.cache.TemplateCache.getTemplateInternal(TemplateCache.java:439)
	    at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:292)
	    at freemarker.template.Configuration.getTemplate(Configuration.java:2750)
	    at freemarker.template.Configuration.getTemplate(Configuration.java:2599)
	    at io.micronaut.views.freemarker.FreemarkerViewsRenderer.exists(FreemarkerViewsRenderer.java:106)
	    at io.micronaut.views.ViewsFilter.lambda$doFilter$0(ViewsFilter.java:130)

this is b/c ParseException is a IOException

**Comment by jameskleeh** [comment]
Where is it getting swallowed at? If you have an example that would make it easy to track down

**Comment by jameskleeh** [comment]
@Andy2003 Please upload an example. I don't know enough about freemarker to know what a malformed template would be.

**Comment by Andy2003** [comment]
@jameskleeh I added a test case

**Comment by yallara** [comment]
I've had the same problem. I think it is due to an incorrect import. 

io.micronaut.views.freemarker.FreemarkerViewsRenderer imports io.micronaut.core.cli.exceptions.ParseException which is caught at line 87. However the try block doesn't seem to ever throw that Exception. It does, however, throw freemarker.core.ParseException which I believe is the one intended to be caught.

In which case, the fix is to remove the incorrect import so the correct ParseException is caught.

**Comment by ilopmar** [comment]
I've put @Andy2003 test and @yallara comment in this PR https://github.com/micronaut-projects/micronaut-views/pull/97. As you can see, now the right error message is displayed:

```
Caused by: freemarker.core.ParseException: Syntax error in template "invalid.ftl" in line 23, column 8:
Unexpected end of file reached. You have an unclosed #if.
```
