### ISSUE TITLE
Allow multiple ViewRenderer on the classpath

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-views#256]
### Feature description

At the moment, if more then one ViewRender is on the classpath then you get a following exception (in v1.3.2):

```
io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.views.rocker.RockerViewsRenderer, io.micronaut.views.handlebars.HandlebarsViewsRenderer]
    at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1817)
    at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:403)
    at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:2405)
    at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2318)
    at io.micronaut.context.DefaultBeanContext.lambda$findConcreteCandidate$58(DefaultBeanContext.java:2271)
    at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
    at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
    at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
    at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2270)
    at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2059)
    at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1113)
    at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:626)
    at io.micronaut.views.ViewsFilter.lambda$doFilter$0(ViewsFilter.java:120)
```

Ideally, `ViewsFiltrer` is querying the list of beans and use the one for which the templates exists. And/or there is some discriminator value in the `View` annotation to tell Micronaut in which renderer should be used.

**Comment by ilopmar** [comment]
Not 100% sure but I think we fixed this issue a long time ago. Can you try with a newer version?

**Comment by musketyr** [comment]
I've checked the code in the `master` branch and it still uses `findBean` instead if `getBeansOfType`:

https://github.com/micronaut-projects/micronaut-views/blob/master/views-core/src/main/java/io/micronaut/views/ViewsFilter.java#L91

**Comment by ilopmar** [comment]
PRs welcome :smiley:

**Comment by rferreira** [comment]
@musketyr I'm assuming here that you have multiple ViewRenders for the same Media Type - what would be the use case for that?

**Comment by musketyr** [comment]
Yes. We have Handlebars historically for rendering email templates and we
wanted to add Rocker for rendering some primitive landing pages. Both of
them registers renders for HTML.

so 7. 8. 2021 v 3:46 odesílatel Rafael Ferreira ***@***.***>
napsal:

**Comment by sdelamo** [comment]
I think we can release this feature as part of the 2.x branch. @musketyr and everyone let me know if the PR I wrote fulfils your requirements.

**Comment by musketyr** [comment]
This looks good to me. If I understand the PR, it loads all the views for the content type, and orders them by priority. Then it checks one by one if the view for given render exists and render the first available, right?

**Comment by sdelamo** [comment]
>  it loads all the views for the content type, and orders them by priority. 

It loads the `ViewsRenderer`

**Comment by musketyr** [comment]
Ok, thanks for explanation. This is a great improvement. It will be great if it can be merged into 2.x

**Comment by sdelamo** [comment]
@musketyr 2.4.0 contains this feature.

**Comment by musketyr** [comment]
Thank you
