### ISSUE TITLE
SecurityViewModelProcessor throws UnsopportedException for unmodifiable models

### ISSUE THREAD

**Issue by johndevs** [micronaut-projects/micronaut-views#309]
### Expected Behavior

When using an unmodifiable Map as a model for a view then SecurityViewModelProcessor with throw an exception.

See:
https://github.com/micronaut-projects/micronaut-views/blob/master/views-core/src/main/java/io/micronaut/views/model/security/SecurityViewModelProcessor.java#L70

### Actual Behaviour

When using a view where the model is set to an unmodifiable map, an exception is thrown.

e.g

```
return new ModelAndView("myview", Map.of("foo","bar"));
```

Will throw
```
java.lang.UnsupportedOperationException: null
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.putIfAbsent(ImmutableCollections.java:1074)
	at io.micronaut.views.model.security.SecurityViewModelProcessor.process(SecurityViewModelProcessor.java:70)
	at io.micronaut.views.DefaultViewsModelDecorator.lambda$decorate$1(DefaultViewsModelDecorator.java:62)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.micronaut.views.DefaultViewsModelDecorator.decorate(DefaultViewsModelDecorator.java:62)
	at io.micronaut.views.ViewsFilter.lambda$doFilter$0(ViewsFilter.java:96)
```

### Steps To Reproduce

1. Create a method that returns a ModelAndView
2. Set the view to a UnmodifableMap

### Environment Information

- Ubuntu
- JDK 17

### Version

3.1.1

**Comment by johndevs** [comment]
Thanks for fixing this up @guillermocalvo @timyates! This will simplify things a lot :partying_face:
